# Generated by Django 3.1.1 on 2020-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
